development:
  adapter: async
  url: redis://127.0.0.1:6379/0
  channel_prefix: CableChat_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: CableChat_production
